# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.llm import llm_pb2 as yeying_dot_api_dot_llm_dot_llm__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in yeying/api/llm/llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LlmStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Translate = channel.unary_unary(
                '/yeying.api.llm.Llm/Translate',
                request_serializer=yeying_dot_api_dot_llm_dot_llm__pb2.TranslateRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_llm_dot_llm__pb2.TranslateResponse.FromString,
                _registered_method=True)
        self.Complete = channel.unary_stream(
                '/yeying.api.llm.Llm/Complete',
                request_serializer=yeying_dot_api_dot_llm_dot_llm__pb2.CompleteRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_llm_dot_llm__pb2.CompleteResponse.FromString,
                _registered_method=True)
        self.Edit = channel.unary_stream(
                '/yeying.api.llm.Llm/Edit',
                request_serializer=yeying_dot_api_dot_llm_dot_llm__pb2.EditRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_llm_dot_llm__pb2.EditResponse.FromString,
                _registered_method=True)
        self.Generate = channel.unary_stream(
                '/yeying.api.llm.Llm/Generate',
                request_serializer=yeying_dot_api_dot_llm_dot_llm__pb2.GenerateRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_llm_dot_llm__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.Speech = channel.unary_unary(
                '/yeying.api.llm.Llm/Speech',
                request_serializer=yeying_dot_api_dot_llm_dot_llm__pb2.SpeechRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_llm_dot_llm__pb2.SpeechResponse.FromString,
                _registered_method=True)


class LlmServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Translate(self, request, context):
        """不同语言的文字翻译工作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Complete(self, request, context):
        """内容补全
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Edit(self, request, context):
        """编辑图片
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Generate(self, request, context):
        """文本生成图片
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Speech(self, request, context):
        """文本生语音
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Translate': grpc.unary_unary_rpc_method_handler(
                    servicer.Translate,
                    request_deserializer=yeying_dot_api_dot_llm_dot_llm__pb2.TranslateRequest.FromString,
                    response_serializer=yeying_dot_api_dot_llm_dot_llm__pb2.TranslateResponse.SerializeToString,
            ),
            'Complete': grpc.unary_stream_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=yeying_dot_api_dot_llm_dot_llm__pb2.CompleteRequest.FromString,
                    response_serializer=yeying_dot_api_dot_llm_dot_llm__pb2.CompleteResponse.SerializeToString,
            ),
            'Edit': grpc.unary_stream_rpc_method_handler(
                    servicer.Edit,
                    request_deserializer=yeying_dot_api_dot_llm_dot_llm__pb2.EditRequest.FromString,
                    response_serializer=yeying_dot_api_dot_llm_dot_llm__pb2.EditResponse.SerializeToString,
            ),
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=yeying_dot_api_dot_llm_dot_llm__pb2.GenerateRequest.FromString,
                    response_serializer=yeying_dot_api_dot_llm_dot_llm__pb2.GenerateResponse.SerializeToString,
            ),
            'Speech': grpc.unary_unary_rpc_method_handler(
                    servicer.Speech,
                    request_deserializer=yeying_dot_api_dot_llm_dot_llm__pb2.SpeechRequest.FromString,
                    response_serializer=yeying_dot_api_dot_llm_dot_llm__pb2.SpeechResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yeying.api.llm.Llm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yeying.api.llm.Llm', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Llm(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Translate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yeying.api.llm.Llm/Translate',
            yeying_dot_api_dot_llm_dot_llm__pb2.TranslateRequest.SerializeToString,
            yeying_dot_api_dot_llm_dot_llm__pb2.TranslateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/yeying.api.llm.Llm/Complete',
            yeying_dot_api_dot_llm_dot_llm__pb2.CompleteRequest.SerializeToString,
            yeying_dot_api_dot_llm_dot_llm__pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Edit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/yeying.api.llm.Llm/Edit',
            yeying_dot_api_dot_llm_dot_llm__pb2.EditRequest.SerializeToString,
            yeying_dot_api_dot_llm_dot_llm__pb2.EditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/yeying.api.llm.Llm/Generate',
            yeying_dot_api_dot_llm_dot_llm__pb2.GenerateRequest.SerializeToString,
            yeying_dot_api_dot_llm_dot_llm__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Speech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yeying.api.llm.Llm/Speech',
            yeying_dot_api_dot_llm_dot_llm__pb2.SpeechRequest.SerializeToString,
            yeying_dot_api_dot_llm_dot_llm__pb2.SpeechResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
