# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from yeying.api.config import config_pb2 as yeying_dot_api_dot_config_dot_config__pb2


class ConfigStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Set = channel.unary_unary(
                '/yeying.api.config.Config/Set',
                request_serializer=yeying_dot_api_dot_config_dot_config__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_config_dot_config__pb2.SetConfigResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/yeying.api.config.Config/Get',
                request_serializer=yeying_dot_api_dot_config_dot_config__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_config_dot_config__pb2.GetConfigResponse.FromString,
                )


class ConfigServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=yeying_dot_api_dot_config_dot_config__pb2.SetConfigRequest.FromString,
                    response_serializer=yeying_dot_api_dot_config_dot_config__pb2.SetConfigResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=yeying_dot_api_dot_config_dot_config__pb2.GetConfigRequest.FromString,
                    response_serializer=yeying_dot_api_dot_config_dot_config__pb2.GetConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yeying.api.config.Config', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Config(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yeying.api.config.Config/Set',
            yeying_dot_api_dot_config_dot_config__pb2.SetConfigRequest.SerializeToString,
            yeying_dot_api_dot_config_dot_config__pb2.SetConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yeying.api.config.Config/Get',
            yeying_dot_api_dot_config_dot_config__pb2.GetConfigRequest.SerializeToString,
            yeying_dot_api_dot_config_dot_config__pb2.GetConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
