# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.interviewer import room_pb2 as yeying_dot_api_dot_interviewer_dot_room__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in yeying/api/interviewer/room_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoomStub(object):
    """*
    面试间管理模块
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/yeying.api.apps.interviewer.Room/Create',
                request_serializer=yeying_dot_api_dot_interviewer_dot_room__pb2.CreateRoomRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_interviewer_dot_room__pb2.CreateRoomResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/yeying.api.apps.interviewer.Room/Get',
                request_serializer=yeying_dot_api_dot_interviewer_dot_room__pb2.GetRoomRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_interviewer_dot_room__pb2.GetRoomResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/yeying.api.apps.interviewer.Room/Update',
                request_serializer=yeying_dot_api_dot_interviewer_dot_room__pb2.UpdateRoomRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_interviewer_dot_room__pb2.UpdateRoomResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/yeying.api.apps.interviewer.Room/Delete',
                request_serializer=yeying_dot_api_dot_interviewer_dot_room__pb2.DeleteRoomRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_interviewer_dot_room__pb2.DeleteRoomResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/yeying.api.apps.interviewer.Room/List',
                request_serializer=yeying_dot_api_dot_interviewer_dot_room__pb2.ListRoomsRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_interviewer_dot_room__pb2.ListRoomsResponse.FromString,
                _registered_method=True)


class RoomServicer(object):
    """*
    面试间管理模块
    """

    def Create(self, request, context):
        """创建面试间 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """获取面试间信息 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """更新面试间 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """删除面试间 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """列出面试间 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=yeying_dot_api_dot_interviewer_dot_room__pb2.CreateRoomRequest.FromString,
                    response_serializer=yeying_dot_api_dot_interviewer_dot_room__pb2.CreateRoomResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=yeying_dot_api_dot_interviewer_dot_room__pb2.GetRoomRequest.FromString,
                    response_serializer=yeying_dot_api_dot_interviewer_dot_room__pb2.GetRoomResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=yeying_dot_api_dot_interviewer_dot_room__pb2.UpdateRoomRequest.FromString,
                    response_serializer=yeying_dot_api_dot_interviewer_dot_room__pb2.UpdateRoomResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=yeying_dot_api_dot_interviewer_dot_room__pb2.DeleteRoomRequest.FromString,
                    response_serializer=yeying_dot_api_dot_interviewer_dot_room__pb2.DeleteRoomResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=yeying_dot_api_dot_interviewer_dot_room__pb2.ListRoomsRequest.FromString,
                    response_serializer=yeying_dot_api_dot_interviewer_dot_room__pb2.ListRoomsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yeying.api.apps.interviewer.Room', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yeying.api.apps.interviewer.Room', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Room(object):
    """*
    面试间管理模块
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yeying.api.apps.interviewer.Room/Create',
            yeying_dot_api_dot_interviewer_dot_room__pb2.CreateRoomRequest.SerializeToString,
            yeying_dot_api_dot_interviewer_dot_room__pb2.CreateRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yeying.api.apps.interviewer.Room/Get',
            yeying_dot_api_dot_interviewer_dot_room__pb2.GetRoomRequest.SerializeToString,
            yeying_dot_api_dot_interviewer_dot_room__pb2.GetRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yeying.api.apps.interviewer.Room/Update',
            yeying_dot_api_dot_interviewer_dot_room__pb2.UpdateRoomRequest.SerializeToString,
            yeying_dot_api_dot_interviewer_dot_room__pb2.UpdateRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yeying.api.apps.interviewer.Room/Delete',
            yeying_dot_api_dot_interviewer_dot_room__pb2.DeleteRoomRequest.SerializeToString,
            yeying_dot_api_dot_interviewer_dot_room__pb2.DeleteRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yeying.api.apps.interviewer.Room/List',
            yeying_dot_api_dot_interviewer_dot_room__pb2.ListRoomsRequest.SerializeToString,
            yeying_dot_api_dot_interviewer_dot_room__pb2.ListRoomsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
