# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.rag import context_pb2 as yeying_dot_api_dot_rag_dot_context__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in yeying/api/rag/context_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContextStub(object):
    """*
    上下文知识库管理模块
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/yeying.api.rag.Context/Create',
                request_serializer=yeying_dot_api_dot_rag_dot_context__pb2.CreateContextRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.CreateContextResponse.FromString,
                _registered_method=True)
        self.Add = channel.unary_unary(
                '/yeying.api.rag.Context/Add',
                request_serializer=yeying_dot_api_dot_rag_dot_context__pb2.AddContextRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.AddContextResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/yeying.api.rag.Context/Delete',
                request_serializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextResponse.FromString,
                _registered_method=True)
        self.DeleteMessage = channel.unary_unary(
                '/yeying.api.rag.Context/DeleteMessage',
                request_serializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextMessageRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextMessageResponse.FromString,
                _registered_method=True)


class ContextServicer(object):
    """*
    上下文知识库管理模块
    """

    def Create(self, request, context):
        """创建知识库 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Add(self, request, context):
        """添加消息到知识库 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """删除知识库中的URL 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMessage(self, request, context):
        """删除知识库中URL的某条Message 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContextServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.CreateContextRequest.FromString,
                    response_serializer=yeying_dot_api_dot_rag_dot_context__pb2.CreateContextResponse.SerializeToString,
            ),
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.AddContextRequest.FromString,
                    response_serializer=yeying_dot_api_dot_rag_dot_context__pb2.AddContextResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextRequest.FromString,
                    response_serializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextResponse.SerializeToString,
            ),
            'DeleteMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMessage,
                    request_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextMessageRequest.FromString,
                    response_serializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yeying.api.rag.Context', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yeying.api.rag.Context', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Context(object):
    """*
    上下文知识库管理模块
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yeying.api.rag.Context/Create',
            yeying_dot_api_dot_rag_dot_context__pb2.CreateContextRequest.SerializeToString,
            yeying_dot_api_dot_rag_dot_context__pb2.CreateContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yeying.api.rag.Context/Add',
            yeying_dot_api_dot_rag_dot_context__pb2.AddContextRequest.SerializeToString,
            yeying_dot_api_dot_rag_dot_context__pb2.AddContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yeying.api.rag.Context/Delete',
            yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextRequest.SerializeToString,
            yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yeying.api.rag.Context/DeleteMessage',
            yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextMessageRequest.SerializeToString,
            yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
