# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from yeying.api.rag import context_pb2 as yeying_dot_api_dot_rag_dot_context__pb2


class ContextStub(object):
    """*
    上下文知识库管理模块
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/yeying.api.rag.Context/Create',
                request_serializer=yeying_dot_api_dot_rag_dot_context__pb2.CreateContextRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.CreateContextResponse.FromString,
                )
        self.Add = channel.unary_unary(
                '/yeying.api.rag.Context/Add',
                request_serializer=yeying_dot_api_dot_rag_dot_context__pb2.AddContextRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.AddContextResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/yeying.api.rag.Context/Delete',
                request_serializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextResponse.FromString,
                )
        self.DeleteMessage = channel.unary_unary(
                '/yeying.api.rag.Context/DeleteMessage',
                request_serializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextMessageRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextMessageResponse.FromString,
                )


class ContextServicer(object):
    """*
    上下文知识库管理模块
    """

    def Create(self, request, context):
        """创建知识库 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Add(self, request, context):
        """添加消息到知识库 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """删除知识库中的URL 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMessage(self, request, context):
        """删除知识库中URL的某条Message 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContextServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.CreateContextRequest.FromString,
                    response_serializer=yeying_dot_api_dot_rag_dot_context__pb2.CreateContextResponse.SerializeToString,
            ),
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.AddContextRequest.FromString,
                    response_serializer=yeying_dot_api_dot_rag_dot_context__pb2.AddContextResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextRequest.FromString,
                    response_serializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextResponse.SerializeToString,
            ),
            'DeleteMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMessage,
                    request_deserializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextMessageRequest.FromString,
                    response_serializer=yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yeying.api.rag.Context', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Context(object):
    """*
    上下文知识库管理模块
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yeying.api.rag.Context/Create',
            yeying_dot_api_dot_rag_dot_context__pb2.CreateContextRequest.SerializeToString,
            yeying_dot_api_dot_rag_dot_context__pb2.CreateContextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yeying.api.rag.Context/Add',
            yeying_dot_api_dot_rag_dot_context__pb2.AddContextRequest.SerializeToString,
            yeying_dot_api_dot_rag_dot_context__pb2.AddContextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yeying.api.rag.Context/Delete',
            yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextRequest.SerializeToString,
            yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yeying.api.rag.Context/DeleteMessage',
            yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextMessageRequest.SerializeToString,
            yeying_dot_api_dot_rag_dot_context__pb2.DeleteContextMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
